- storage/src/iterator/concat_iterator.rs
As titled.
Ref: #1 
Close: #11 #14
> feat: impl binary seek for concat iter

- storage/src/sstable/block.rs
- storage/src/sstable/utils.rs
> feat: varint coding for key prefix

- Cargo.lock
- codecov.yml
- storage/Cargo.toml
- storage/src/error.rs
- storage/src/lib.rs
- storage/src/object_store/mem.rs
- storage/src/object_store/mod.rs
- storage/src/object_store/s3.rs
> feat: object store trait and mem impl for test

- Cargo.lock
- storage/Cargo.toml
- storage/src/error.rs
- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/block_cache.rs
- storage/src/lsm_tree/components/mod.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/object_store/mod.rs
> feat: impl sstable store with simple block cache

- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/mod.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
> fix: 2 as test restart interval

- .github/workflows/main.yml
- README.md
> chore: add ci and codecov badge in README

- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/mod.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/mod.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/mod.rs
> feat: sstable iterator

- storage/src/lib.rs
- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/merge_iterator.rs
- storage/src/lsm_tree/iterator/mod.rs
> feat: merge iterator

- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/merge_iterator.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
As titled. A **FIX ME** left.
Ref: #26 #25
> test: add seek-forward-backward iterate test

- storage/src/lsm_tree/iterator/block_iterator.rs
> fix: avoid binary search for restart point when block iter move prev

- Makefile.toml
- rudder/src/store/object.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/object_store/mem.rs
- storage/src/object_store/mod.rs
- storage/src/object_store/s3.rs
> fix: object store get returns option

- storage/src/lsm_tree/manifest/version.rs
> fix: pick overkap sst with timestamp

- storage/src/lsm_tree/components/mod.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/lsm_tree/manifest/version.rs
- storage/src/lsm_tree/utils/bloom.rs
- storage/src/lsm_tree/utils/mod.rs
> feat: pick overlap ssts by key with bloom filter

- storage/src/lsm_tree/utils/coding.rs
Go to sleep now. DO NOT WRITE CODE WHEN YOU ARE EXHAUSTED AND LACK OF SLEEP.
> fix: revert fix 47

- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/iterator/user_key_iterator.rs
- storage/src/lsm_tree/manifest/version.rs
> refactor: refactor Sstable and SstableStore abstractions

- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/memtable_iterator.rs
- storage/src/lsm_tree/iterator/merge_iterator.rs
- storage/src/lsm_tree/iterator/mod.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/iterator/user_key_iterator.rs
- storage/src/lsm_tree/s3_lsm_tree.rs
`seek` returns a bool result which means a visible version of the given seek condition is found in this iterator (but can be existing or be deleted).
Fix: #53 .
Ref: #44 .
> feat: seek return that if a visible verion of the  given key is found

- .github/template/template.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- Cargo.lock
- etc/rudder.toml
- proto/src/proto/rudder.proto
- rudder/src/config.rs
- rudder/src/lib.rs
- rudder/src/main.rs
- rudder/src/service.rs
- storage/src/lsm_tree/manifest/error.rs
- storage/src/lsm_tree/manifest/version.rs
- storage/src/lsm_tree/mod.rs
- tests/Cargo.toml
- tests/etc/rudder.toml
- tests/etc/wheel.toml
- tests/integrations/mod.rs
- wheel/Cargo.toml
- wheel/src/config.rs
- wheel/src/error.rs
- wheel/src/lib.rs
- wheel/src/lsm_tree/mod.rs
- wheel/src/lsm_tree/object_store_lsm_tree.rs
- wheel/src/lsm_tree/sstable_uploader.rs
- wheel/src/lsm_tree/wheel_version_manager.rs
- wheel/src/main.rs
- wheel/src/service.rs
As titled. Fix bugs and use rudder and wheel in integration test directly.
*This PR also introduced a lot of commented `println` for debug.. Remove them later.*
Ref: #30 .
> feat: use rudder and wheel in integration test directly

- Cargo.lock
- etc/exhauster.toml
- etc/rudder.toml
- etc/wheel.toml
- exhauster/Cargo.toml
- exhauster/src/compaction_filter.rs
- exhauster/src/config.rs
- exhauster/src/error.rs
- exhauster/src/lib.rs
- exhauster/src/main.rs
- exhauster/src/service.rs
- proto/build.rs
- proto/src/lib.rs
- proto/src/proto/exhauster.proto
- storage/src/lsm_tree/utils/coding.rs
- tests/etc/rudder.toml
- tests/etc/wheel.toml
- wheel/src/worker/sstable_uploader.rs
As titled. Not included in integration tests for now.
> feat: add exhauster skeleton

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- exhauster/src/lib.rs
- exhauster/src/partitioner.rs
- exhauster/src/service.rs
- proto/src/proto/exhauster.proto
- proto/src/proto/rudder.proto
- rudder/Cargo.toml
- rudder/src/lib.rs
- rudder/src/meta/mem.rs
- rudder/src/meta/mod.rs
- rudder/src/meta/object.rs
- rudder/src/service.rs
- rudder/src/store/mod.rs
- rudder/src/worker/compactor.rs
- rudder/src/worker/mod.rs
- wheel/Cargo.toml
- wheel/src/lib.rs
- wheel/src/worker/mod.rs
- wheel/src/worker/sstable_uploader.rs
- wheel/src/worker/version_syncer.rs
> feat: introduce partitioenr

- Cargo.lock
- exhauster/src/lib.rs
- proto/src/lib.rs
- proto/src/proto/meta.proto
- proto/src/proto/rudder.proto
- proto/src/proto/wheel.proto
- rudder/src/lib.rs
- rudder/src/service.rs
- rudder/src/worker/compactor.rs
- tests/Cargo.toml
- tests/integrations/mod.rs
- wheel/src/lib.rs
- wheel/src/meta/mem.rs
- wheel/src/meta/mod.rs
- wheel/src/meta/object.rs
- wheel/src/service.rs
- wheel/src/worker/heartbeater.rs
- wheel/src/worker/mod.rs
> feat: impl update key ranges rpc

- etc/rudder.toml
- rudder/src/worker/compactor.rs
> refactor: refine compactor code

- Cargo.lock
- common/Cargo.toml
- common/src/coding.rs
- common/src/config.rs
- common/src/lib.rs
- etc/lsm_tree.toml
- etc/rudder.toml
- exhauster/src/config.rs
- exhauster/src/service.rs
- rudder/src/config.rs
- rudder/src/worker/compactor.rs
- storage/Cargo.toml
- storage/src/error.rs
- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/manifest/version.rs
- storage/src/lsm_tree/utils/coding.rs
- tests/etc/lsm_tree.toml
- tests/etc/rudder.toml
- tests/etc/wheel.toml
- tests/integrations/mod.rs
- wheel/src/config.rs
- wheel/src/storage/lsm_tree.rs
- wheel/src/worker/sstable_uploader.rs
> refactor: move common configs to common

- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/lsm_tree/iterator/block_iterator.rs
> feat: remove unnecessary slice copy

- exhauster/src/service.rs
- proto/src/proto/exhauster.proto
- proto/src/proto/manifest.proto
- proto/src/proto/rudder.proto
- rudder/src/meta/mem.rs
- rudder/src/meta/mod.rs
- rudder/src/service.rs
- rudder/src/worker/compactor.rs
- storage/src/lsm_tree/manifest/version.rs
- wheel/src/worker/sstable_uploader.rs
> feat: simple tso

- Cargo.lock
- common/Cargo.toml
- common/src/channel_pool.rs
- common/src/config.rs
- common/src/lib.rs
- etc/exhauster.toml
- etc/wheel.toml
- exhauster/src/config.rs
- exhauster/src/lib.rs
- exhauster/src/worker/heartbeater.rs
- rudder/src/lib.rs
- rudder/src/meta/mem.rs
- rudder/src/meta/mod.rs
- rudder/src/service.rs
- rudder/src/worker/compaction_detector.rs
- tests/etc/exhauster.toml
- tests/etc/wheel.toml
- tests/integrations/mod.rs
- wheel/src/config.rs
- wheel/src/error.rs
- wheel/src/lib.rs
- wheel/src/main.rs
- wheel/src/worker/heartbeater.rs
- wheel/src/worker/sstable_uploader.rs
> feat: implement connection channel pool and delay connect

- .github/template/template.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
> ci: use actions to install nextest and cargo-llvm-cov

- exhauster/src/service.rs
- rudder/src/meta/mem.rs
- rudder/src/worker/compaction_detector.rs
- storage/src/lsm_tree/manifest/version.rs
- wheel/src/storage/lsm_tree.rs
- wheel/src/worker/sstable_uploader.rs
For more details, see #85 .
Fix #85 .
> fix: compaction pick overlapping sstables by range

- storage/src/error.rs
- storage/src/raftstore/entry.rs
- storage/src/raftstore/log.rs
- storage/src/raftstore/mod.rs
> impl: basic raft log write

- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/components/gear.rs
- wheel/src/components/mod.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/service.rs
Separate FSM apply with raft log store apply.
Part of work to combine WAL and raft log store.
Ref: #88 .
> feat: separate fsm apply with raft log store

- Cargo.lock
- storage/src/raft_log_store/mod.rs
- storage/src/raft_log_store/store.rs
- wheel/Cargo.toml
- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/components/gear.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/components/mod.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
- wheel/src/worker/mod.rs
As titled.
Create a `Gear` and a `KvWorker` for each raft instance.
Ref: #88 .
> feat: gear and kv worker per raft instance

- storage/src/raft_log_store/block_cache.rs
- storage/src/raft_log_store/entry.rs
- storage/src/raft_log_store/store.rs
> feat: fill cache after append raft log

- Cargo.lock
- proto/Cargo.toml
- proto/build.rs
- proto/src/lib.rs
- proto/src/proto/kv.proto
- proto/src/proto/wheel.proto
- wheel/src/components/command.rs
- wheel/src/components/gear.rs
- wheel/src/components/raft_manager.rs
- wheel/src/worker/kv.rs
As titled.
TODO: attach a doc later.
Ref: #88 .
> feat: impl applier skeleton, revert gear channel separation

- proto/src/proto/wheel.proto
- tests/integrations/mod.rs
- wheel/src/components/raft_manager.rs
- wheel/src/error.rs
- wheel/src/meta/mem.rs
- wheel/src/meta/mod.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
Implement wheel services for bootstrapping raft groups:
- `add_endpoints`
- `add_key_range`
- `initialize_raft_group`
Ref: #88 .
> feat: impl add_endpoints, add_key_range, initialize_raft_group service

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- common/src/notify_pool.rs
- proto/src/lib.rs
- wheel/src/components/command.rs
- wheel/src/components/gear.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
As titled. For request serving.
> feat: impl notify pool

- common/src/notify_pool.rs
- wheel/src/components/command.rs
- wheel/src/components/raft_manager.rs
- wheel/src/error.rs
- wheel/src/lib.rs
- wheel/src/meta/mem.rs
- wheel/src/meta/mod.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
As titled.
TODO: Serve kv service only by wheel and adapt integration tests.
Ref: #88 .
> feat: notify after apply with notify pool

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- common/src/time.rs
- proto/src/proto/kv.proto
- tests/integrations/mod.rs
- wheel/src/components/command.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/components/raft_manager.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
Binding RAFT and LSM-tree TOGETHER!!
...and QPS drops x200, 😇.
Prepared to run.
> feat: bind raft and lsm-tree together!

- Cargo.lock
- Makefile.toml
- common/Cargo.toml
- common/src/lib.rs
- common/src/log.rs
- common/src/time.rs
- exhauster/Cargo.toml
- make/jaeger.toml
- rudder/Cargo.toml
- tests/Cargo.toml
- tests/integrations/mod.rs
- wheel/Cargo.toml
- wheel/src/components/raft_log_store.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
Add jaeger support for tracing.
Ref: #118 .
> feat: introduce jaeger support for tracing

- Cargo.toml
- common/src/log.rs
- tests/Cargo.toml
- tests/integrations/mod.rs
> feat: control enable/disable tracing with env

- Makefile.toml
- etc/prometheus.yml
- make/grafana.toml
- make/prometheus.toml
- tests/integrations/mod.rs
> fix: fix cargo make scripts

- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/store.rs
- tests/integrations/mod.rs
- wheel/src/service.rs
- wheel/src/worker/raft.rs
> test: test multi raft groups

- Cargo.lock
- tests/Cargo.toml
- tests/etc/exhauster.toml
- tests/etc/port.toml
- tests/etc/rudder.toml
- tests/etc/wheel.toml
- tests/integrations/lib.rs
- tests/integrations/test_concurrent_put_get.rs
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
> test: enable both multi-group and single-group test

- etc/grafana-dashboards/runkv-overview.json
- wheel/src/service.rs
- wheel/src/worker/raft.rs
> feat: replace rate with irate in metrics and intrduce more metrics

- Cargo.lock
- Cargo.toml
- Makefile
- bench/Cargo.toml
- bench/bench_kv/main.rs
- bench/etc/exhauster.toml
- bench/etc/lsm_tree.toml
- bench/etc/rudder.toml
- bench/etc/wheel.toml
- codecov.yml
- common/src/log.rs
- etc/grafana-dashboards/runkv-overview.json
- etc/prometheus.yml
- tests/etc/prometheus.yml
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
- wheel/src/components/lsm_tree.rs
As titled.
Run default kv bench (in release mode):
```bash
./run d
make bench_kv
./run k
```
Ref: #126 .
> bench: add integration bench

- Cargo.lock
- bench/Cargo.toml
- bench/bench_kv/main.rs
- common/Cargo.toml
- common/src/lib.rs
- common/src/packer.rs
- common/src/sharded_hash_map.rs
- etc/grafana-dashboards/runkv-overview.json
- exhauster/Cargo.toml
- exhauster/src/main.rs
- rudder/Cargo.toml
- rudder/src/main.rs
- wheel/Cargo.toml
- wheel/src/components/fsm.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/components/raft_manager.rs
- wheel/src/components/raft_network.rs
- wheel/src/lib.rs
- wheel/src/main.rs
- wheel/src/service.rs
- wheel/src/trace.rs
- wheel/src/worker/raft.rs
Changes:
- Introduce `Packer` for batching commands in proposals and messages.
- Add metrics for batch size.
- Use `jemalloc` as default memory allocator in bench and binaries.
P.S. No obvious boost for performance.
> feat: introduce Packer for batching

- common/src/sharded_hash_map.rs
- etc/grafana-dashboards/runkv-overview.json
- storage/src/lsm_tree/components/metrics.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/metrics.rs
- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/service.rs
- wheel/src/trace.rs
- wheel/src/worker/raft.rs
> feat: add TRACE_CTX for timeline tracing, increase metris precision

- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/components/mod.rs
- wheel/src/components/raft_manager.rs
- wheel/src/components/read_only_cmd_pool.rs
- wheel/src/lib.rs
- wheel/src/worker/raft.rs
> feat: use raft read index to serve read only requests

- Cargo.lock
- bench/etc/lsm_tree.toml
- bench/etc/wheel.toml
- etc/wheel.toml
- exhauster/src/lib.rs
- rudder/src/lib.rs
- storage/bench/file_cache_bench/bench.rs
- storage/benches/bench_block_iter.rs
- storage/src/error.rs
- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/block_cache.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/components/sstable_store.rs
- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/merge_iterator.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/iterator/user_key_iterator.rs
- storage/src/lsm_tree/manifest/version.rs
- storage/src/tiered_cache/file_cache/cache.rs
- storage/src/tiered_cache/file_cache/metrics.rs
- storage/src/tiered_cache/mod.rs
- tests/etc/lsm_tree.toml
- tests/etc/wheel.toml
- tests/integrations/test_concurrent_put_get.rs
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
- tests/src/lib.rs
- wheel/src/config.rs
- wheel/src/lib.rs
Integrate tiered cache into RunKV and modify default block size up to 1 MiB.
#177 #178 
ut + it
Please let me graduate.
> feat: integrate tiered cache into RunKV

- etc/grafana-dashboards/runkv-overview.json
Introduce file cache metrics.
#179 
Anyway.
> feat: introduce file cache metrics

- Makefile.toml
- tests/integrations/test_concurrent_put_get.rs
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
- tests/src/lib.rs
Support minio store as object store for bench kv.
#150 
its
Whatever.
> feat: support minio store for bench kv

- Makefile.toml
- etc/grafana-dashboards/runkv-overview.json
- storage/src/lsm_tree/components/metrics.rs
- tests/src/lib.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/worker/raft.rs
Add more metrics and optimize raft clients by reducing clones.
None
uts & its
😷
> feat: add more metrics and optimize raft client

- common/Cargo.toml
- wheel/Cargo.toml
- wheel/src/worker/raft.rs
Fix tracing for bench kv.
#118 
uts & its
🤪
> fix: tracing for bench kv
