MrCroxx/RunKV

- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/merge_iterator.rs
- storage/src/lsm_tree/iterator/mod.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
Impl bi-direction seek. Fix reversing for `MergeIterator`.
The implementation of backward seek simply does a `prev_until_key`. For the *full key (user key | timestamp)* should not be duplicated, the cost is acceptable.
Ref: #1 #25 
Fix: #26
> feat: impl bi-direction seek

- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/merge_iterator.rs
- storage/src/lsm_tree/iterator/mod.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/iterator/user_key_iterator.rs
- storage/src/lsm_tree/mod.rs
As titled.
- Implement `UserKeyIterator`.
- Fix "backward seek for a key that larger than all keys" for all iterators.
- Refine iterator tests.
Ref: #1 #25 #26
> feat: impl user key iterator

- storage/src/lib.rs
- storage/src/lsm_tree/components/memtable.rs
- storage/src/lsm_tree/iterator/memtable_iterator.rs
- storage/src/lsm_tree/s3_lsm_tree.rs
Expose the timestamp for interfaces of LSMTree.
```plain
Safety: 
The interface exposes `timestamp` to user for the compatibility with upper system. It's
caller's responsibility to ensure that the new timestamp is higher than the old one on the
same key. Otherwise there will be consistency problems.
```
Not fix: #53 .
Ref: #44 .
> feat: expose timestamp for interfaces of lsm-tree

- common/src/config.rs
- storage/src/lsm_tree/components/block.rs
- storage/src/lsm_tree/components/memtable.rs
- storage/src/lsm_tree/iterator/block_iterator.rs
- storage/src/lsm_tree/iterator/concat_iterator.rs
- storage/src/lsm_tree/iterator/memtable_iterator.rs
- storage/src/lsm_tree/iterator/mod.rs
- storage/src/lsm_tree/iterator/sstable_iterator.rs
- storage/src/lsm_tree/manifest/version.rs
- storage/src/lsm_tree/utils/coding.rs
- tests/etc/lsm_tree.toml
*user key* and *timestamp* are supposed to be compared separately.
Consider this example:
```
user key | timestamp (desc)
k1 :         k1 | 999
k2:         k11 | 000
```
If *user key* and *timestamp* are **NOT** compared separately, k2 would be **less than** k1.
> fix: full key compare

- Makefile
- common/src/atomic.rs
- common/src/config.rs
- common/src/lib.rs
- etc/lsm_tree.toml
- exhauster/src/compaction_filter.rs
- rudder/src/error.rs
- rudder/src/lib.rs
- rudder/src/main.rs
- rudder/src/worker/compaction_detector.rs
- rudder/src/worker/mod.rs
- tests/etc/lsm_tree.toml
- wheel/src/storage/lsm_tree.rs
As titled.
**NOTE:** This pr will slow down integration test because high level compaction always involves all ssts of the level. A sstable picking strategy is needed.
Fix:
- Tombstone cannot be simply removed without taking watermark into account.
Ref: #30 .
> feat: implement simple high level compaction

- exhauster/src/compaction_filter.rs
- exhauster/src/service.rs
- rudder/src/worker/compaction_detector.rs
- storage/src/lsm_tree/manifest/version.rs
As titled.
Fix:
- Multi versions of one key should not be split into multi ssts.
Ref:
#30 .
> feat: reduce ssts involved in compaction

- storage/src/raft_log_store/entry.rs
- storage/src/raft_log_store/error.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/mem.rs
- storage/src/raft_log_store/mod.rs
- storage/src/raft_log_store/store.rs
As titled.
Changes:
- Implement basic memory states.
Ref: #88 .
> feat: raft log store (part 2)

- storage/src/raft_log_store/entry.rs
- storage/src/raft_log_store/mem.rs
- storage/src/raft_log_store/store.rs
As titled.
Changes:
- Implement compact and kv operations for `RaftLogStore`.
Ref: #88 .
> feat: raft log store (part 4)

- Cargo.lock
- storage/src/raft_log_store/entry.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/mem.rs
- storage/src/raft_log_store/store.rs
- storage/src/utils/coding.rs
- wheel/Cargo.toml
- wheel/src/error.rs
- wheel/src/storage/mod.rs
- wheel/src/storage/raft_log_store.rs
As titled.
Changes:
- Add `ctx` field to raft log entry meta segment.
- Refactor raft log store.
Ref: #88 .
> feat: impl raft log store (part 5)

- Cargo.lock
- storage/src/raft_log_store/entry.rs
- storage/src/raft_log_store/mem.rs
- storage/src/raft_log_store/store.rs
- wheel/Cargo.toml
- wheel/src/storage/fsm.rs
- wheel/src/storage/mod.rs
- wheel/src/storage/raft_log_store.rs
As titled. 
After adapting and fixing, now `RaftGroupLogStore` can pass openraft test suite `test_all`.
Ref: #88 .
> feat: raft log store pass openraft test suite

- Cargo.lock
- etc/wheel.toml
- tests/Cargo.toml
- tests/etc/wheel.toml
- tests/integrations/mod.rs
- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/components/mod.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/config.rs
- wheel/src/lib.rs
- wheel/src/service.rs
`Gear` is used to forward commands from to the `ObjectLsmTree` asynchronously.
Part of work to combine raft log store and state machine WAL.
Ref: #88 .
> feat: introduce async command and gear

- Cargo.lock
- common/src/channel_pool.rs
- wheel/Cargo.toml
- wheel/src/components/gear.rs
- wheel/src/components/network.rs
- wheel/src/components/raft_manager.rs
- wheel/src/error.rs
- wheel/src/lib.rs
- wheel/src/service.rs
As titled.
Changes:
- Implement raft service.
- Add basic test for raft manager.
- Update openraft dep.
Ref: #88 .
> feat: raft manager (part1)

- storage/Cargo.toml
- storage/benches/bench_block_iter.rs
* fix bugs in `bench_block_iter.rs`, remove async in tests
* run `cargo bench --package runkv-storage` in `storage` dir
https://github.com/MrCroxx/RunKV/issues/96
> fix: remove async in bench_block_iter.rs fix bugs in bench_block_iter.rs

- storage/src/lsm_tree/mod.rs
- tests/integrations/mod.rs
- wheel/src/components/command.rs
- wheel/src/components/gear.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/components/raft_manager.rs
- wheel/src/worker/kv.rs
- wheel/src/worker/mod.rs
Separate apply and snapshot cmd channel in `Gear` and `KvWorker`.
Part of work to combine WAL and raft log store.
Ref: #88 .
> feat: separate apply and snapshot cmd channel

- storage/src/raft_log_store/store.rs
- tests/integrations/mod.rs
- wheel/src/components/network.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
- wheel/src/worker/mod.rs
As titled. Blocks should be indexed by `block_offset` in raft log store block cache.
(What a miracle it could run before....
> fix: fix raft log block cache indexing

- exhauster/src/compaction_filter.rs
- exhauster/src/partitioner.rs
- exhauster/src/service.rs
- rudder/src/service.rs
- storage/src/lsm_tree/components/memtable.rs
- storage/src/lsm_tree/components/sstable.rs
- storage/src/lsm_tree/iterator/memtable_iterator.rs
- storage/src/lsm_tree/iterator/user_key_iterator.rs
- storage/src/lsm_tree/manifest/version.rs
- storage/src/utils/coding.rs
- tests/integrations/mod.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/main.rs
- wheel/src/service.rs
- wheel/src/worker/kv.rs
- wheel/src/worker/sstable_uploader.rs
Separate shared memtable, make each shard writes its own memtable.
State:
Temporarily disable integration tests. Restore it after sequence is refactored and kv client can be used.
> feat: impl memtable per shard (part 1)

- Makefile
- wheel/src/lib.rs
> feat: enable/disable metrics with env

- Cargo.lock
- common/Cargo.toml
- common/src/coding.rs
- common/src/context.rs
- common/src/lib.rs
- common/src/log.rs
- proto/Cargo.toml
- proto/src/lib.rs
- tests/Cargo.toml
- tests/integrations/mod.rs
- wheel/Cargo.toml
- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/lib.rs
- wheel/src/service.rs
- wheel/src/worker/raft.rs
As titled.
Now, operations for tracing (e.g. configuring `follows_form` for spans) are only enabled when building with feature `tracing`.
And opentelemetry subscriber is only enabled with env `RUNKV_TRACE=true`.
So, if you want to do tracing, run commands like this:
`./run k && ./run d && RUNKV_TRACE=true RUST_BACKTRACE=1 cargo test --features tracing --package runkv_tests --test integrations -- test_concurrent_put_get --exact --nocapture`
> feat: use tracing feature to reduce operations for tracing

- Makefile.toml
- etc/grafana-dashboards/runkv-overview.json
- etc/grafana-provisioning/dashboards/runkv-dashboards.yml
- etc/grafana-provisioning/datasources/runkv-prometheus.yml
- etc/grafana.ini
- make/common.toml
- make/grafana.toml
- make/prometheus.toml
- wheel/src/service.rs
- wheel/src/worker/raft.rs
As titled.
Usage:
1. Run `./run d` to bootstrap prometheus and grafana service.
2. Run with `RUNKV_METRICS=true`.
3. Access grafana at `http://localhost:3000`.
Overview:
Ref: #66 .
> feat: add grafana support as metrics service

- Cargo.lock
- Cargo.toml
- client/Cargo.toml
- client/src/lib.rs
- etc/grafana-dashboards/runkv-overview.json
- proto/src/proto/wheel.proto
- tests/Cargo.toml
- wheel/Cargo.toml
- wheel/src/components/raft_network.rs
- wheel/src/service.rs
- wheel/src/worker/raft.rs
Changes:
- Use client-side streaming grpc to reduce raft send messages latency.
- Raft worker get raft clients when init to avoid read lock when sending raft messages.
Summary:
- Raft send messages latency gains barely nothing from client-side streaming grpc or avoiding read lock (Maybe the messages batch is small? Need metrics to further investigate).
- Avoiding read lock benefits the serivce latency.
Ref: #126 .
> feat: using client-side streaming and avoiding read lock to optimize raft message sending

- etc/grafana-dashboards/runkv-overview.json
- proto/src/proto/wheel.proto
- wheel/src/components/raft_network.rs
- wheel/src/service.rs
As titled.
Revert client-side stream rpc.
Ref: #134 .
> feat: send raft message vec in one request

- etc/grafana-dashboards/runkv-overview.json
- wheel/src/service.rs
- wheel/src/worker/raft.rs
Refactor some metrics.
Ref: #66 .
> refactor: refactor some metrics field name and display

- etc/grafana-dashboards/runkv-overview.json
- storage/bench/bench_raft_log_store.rs
- storage/src/raft_log_store/block_cache.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/metrics.rs
- storage/src/raft_log_store/store.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/components/raft_manager.rs
- wheel/src/worker/raft.rs
As titled. 
Now raft log store `append` receives a vector of raft log batch.
More metrics for raft log store are added.
Ref: #126 .
> feat: raft log store append raft log batch vec

- .gitignore
- etc/grafana-dashboards/runkv-overview.json
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/metrics.rs
After printing some metrics and some experiments, `write_all` call is found as the major latency maker for `append`.
This PR reduces the rate of calling `write_all`, and maintains buffer in user space until sync.
main:
HEAD:
Ref: #126 .
> feat: reduce write file rate when append log

- Cargo.lock
- common/Cargo.toml
- common/src/log.rs
- etc/grafana-dashboards/runkv-overview.json
- etc/wheel.toml
- rudder/src/lib.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/store.rs
- tests/etc/wheel.toml
- tests/integrations/test_concurrent_put_get.rs
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
- wheel/src/config.rs
- wheel/src/service.rs
- wheel/src/worker/heartbeater.rs
- wheel/src/worker/raft.rs
Changes:
- Add an empty `VersionDiff` when rudder start, or heartbeater will raise a `VersionDiffExpired` error and immediately send another heartbeat.
- Add more tracing and metrics.
- Add file log support.
> fix: heartbeat raise error if no version diff

- tests/integrations/test_concurrent_put_get.rs
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
Fix #142 .
And this PR increase integration test loop time to 3.
DON'T DRINK WHEN WRITING CODES, 😇.
> fix: fix key generation rule in integration test

- Cargo.lock
- common/Cargo.toml
- common/benches/bench_sharded_hash_map.rs
- common/src/lib.rs
- common/src/sharded_hash_map.rs
`ShardedHashMap` is a sharded hash map which is `Send + Sync`, each shard has its own `RwLock`.
Benchmark (concurrency = 1024):
> feat: introduce sharded hash map

- Cargo.lock
- bench/bench_kv/main.rs
- bench/etc/exhauster.toml
- bench/etc/rudder.toml
- bench/etc/wheel.toml
- proto/src/proto/meta.proto
- proto/src/proto/rudder.proto
- proto/src/proto/wheel.proto
- rudder/src/error.rs
- rudder/src/lib.rs
- rudder/src/meta/mem.rs
- rudder/src/meta/mod.rs
- rudder/src/service.rs
- rudder/src/worker/compaction_detector.rs
- tests/integrations/lib.rs
- wheel/Cargo.toml
- wheel/src/components/fsm.rs
- wheel/src/components/raft_log_store.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/service.rs
- wheel/src/worker/heartbeater.rs
- wheel/src/worker/raft.rs
Introduce `ControlService` in rudder for cluster control (e.g. AddWheels, AddKeyRanges).
Changes:
- Introduce `ControlService` in rudder for cluster control (e.g. AddWheels, AddKeyRanges).
- Refactor `AddWheels(AddEndpoints originally)` and `AddKeyRanges`, make rudder responsible for handling requests and broadcast changes to wheels.
- Refactor bench.
- **IMPORTANT:** Temporarily disable integrations tests. Enable them after runkv client can redirect requests to raft leader.
> feat: impl ControlService for rudder

- Cargo.lock
- bench/Cargo.toml
- bench/bench_kv/main.rs
- client/Cargo.toml
- client/src/client.rs
- client/src/error.rs
- client/src/lib.rs
- client/src/router.rs
- client/src/worker/heartbeater.rs
- client/src/worker/mod.rs
- proto/src/lib.rs
- proto/src/proto/kv.proto
- proto/src/proto/meta.proto
- proto/src/proto/rudder.proto
- rudder/src/meta/mem.rs
- rudder/src/meta/mod.rs
- rudder/src/service.rs
- wheel/src/components/command.rs
- wheel/src/components/fsm.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/service.rs
- wheel/src/worker/heartbeater.rs
- wheel/src/worker/raft.rs
Introduce `RunkvClient`. Which fetch router from rudder and decide target wheel to send requests automatically.
Changes: 
- Introduce `RunkvClient`. Which fetch router from rudder and decide target wheel to send requests automatically.
- Wheel return `Redirect` error if `KvRequest` target is not in itself. *TODO: Return `Redirect` when target is not legal raft leader.*
- Refactor `kv.proto`.
TODOs:
- Return `Redirect` when target is not legal raft leader.
- Restore integration tests with runkv client.
> feat: introduce runkv client

- bench/bench_kv/main.rs
- bench/etc/wheel.toml
- etc/prometheus.yml
- storage/src/raft_log_store/metrics.rs
- wheel/src/components/raft_manager.rs
- wheel/src/lib.rs
- wheel/src/meta/mem.rs
- wheel/src/meta/mod.rs
- wheel/src/service.rs
- wheel/src/worker/heartbeater.rs
- wheel/src/worker/raft.rs
Now `bench_kv --wheels` can input `[1, 10]`.
**NOTE: Each wheel uses its own raft log store. Each raft log store sync itself. So performance will drop sharply if the latency of `fsync` of the disk for raft log store is high.**
> feat: support multi wheel bench (on one node)

- .gitignore
- Makefile
- bench/Cargo.toml
- common/Cargo.toml
- common/src/log.rs
- common/src/notify_pool.rs
- common/src/packer.rs
- etc/grafana-dashboards/runkv-overview.json
- rudder/src/worker/compaction_detector.rs
- storage/Cargo.toml
- storage/src/lsm_tree/manifest/version.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/store.rs
- wheel/Cargo.toml
- wheel/src/components/fsm.rs
- wheel/src/components/lsm_tree.rs
- wheel/src/service.rs
- wheel/src/worker/raft.rs
- Fix deadlock in `runkv_storage::raft_log_store::log`.
- Remove tracing subscriber filter in fmt layer.
- Add `info` logs with `deadlock` feature enabled. Use it with [RunKV Log Matcher](https://github.com/MrCroxx/runkv-log-matcher).
FYI: https://github.com/MrCroxx/RunKV/issues/160#issuecomment-1131482889
Fix: #160 .
There is bug in raft log store index, fix it later. Next Time For Sure!
> fix: fix deadlock in runkv_storage::raft_log_store::log

- storage/src/raft_log_store/entry.rs
- storage/src/raft_log_store/file.rs
- storage/src/raft_log_store/log.rs
- storage/src/raft_log_store/mem.rs
- storage/src/raft_log_store/mod.rs
- storage/src/raft_log_store/store.rs
- wheel/src/components/fsm.rs
Changes:
- Fix data raft when active raft log file read and log rotation happens together.
- Introduce `ActiveFile` and `FrozenFile` to simply `Log` implementation.
Fix: #168 .
> fix: fix raft log store read race

- Cargo.lock
- storage/Cargo.toml
- storage/src/file_cache/buffer.rs
- storage/src/file_cache/error.rs
- storage/src/file_cache/file.rs
- storage/src/file_cache/mod.rs
- storage/src/lib.rs
- tests/integrations/test_concurrent_put_get.rs
- tests/integrations/test_multi_raft_group_concurrent_put_get.rs
Introduce `AlignedBuffer` for further DIO usage.
**NOTE: This PR may break build on MacOS, fix it later.**
#171
> feat: introduce aligned buffer for DIO

- Cargo.lock
- storage/Cargo.toml
- storage/src/file_cache/buffer.rs
- storage/src/file_cache/error.rs
- storage/src/file_cache/file.rs
Introduce file cache skeleton.
#171
> feat: file cache skeleton

- storage/Cargo.toml
- storage/benches/bench_compression.rs
Introduce benchmark for comparing block and stream compression. With stream compression, compressed block size can be better aligned.
Results:
```plain
buffer - vsize: 8B/     time:   [2.1603 us 2.1619 us 2.1634 us]
Found 4 outliers among 100 measurements (4.00%)
1 (1.00%) high mild
3 (3.00%) high severe
block compression - vsize: 8B/
time:   [124.39 us 124.45 us 124.51 us]
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
stream compression - vsize: 8B/
time:   [185.69 us 185.79 us 185.89 us]
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
uncompressed size: 20000
block compressed size: 11887, rate: 0.594
stream compressed size: 11887, rate: 0.594
buffer - vsize: 16B/    time:   [2.8762 us 2.8778 us 2.8794 us]
Found 4 outliers …
```
> bench: compare block and stream compression

- Cargo.lock
- common/Cargo.toml
- storage/Cargo.toml
- storage/src/file_cache/buffer.rs
- storage/src/file_cache/error.rs
- storage/src/file_cache/file.rs
- storage/src/file_cache/file_old.rs
- storage/src/file_cache/fs.rs
- storage/src/file_cache/judge.rs
- storage/src/file_cache/manager.rs
- storage/src/file_cache/mod.rs
- storage/src/lib.rs
Introduce cache file v2. Which is prepared for append-only & punch-hole write model.
#171
> feat: introduce cache file v2
